/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.DamageToUI;
import deepspace.SpaceStationToUI;
import java.util.ArrayList;

/**
 *
 * @author Miguel Ángel Fernández Gutiérrez, Sergio Quijano Rey
 */
public class CurrentStationView extends javax.swing.JPanel {

    private HangarPanel currentHangarPanel;
    private ShieldPanel currentShieldPanel;
    private WeaponPanel currentWeaponPanel;
    
    /**
     * Creates new form CurrentStationView
     */
    public CurrentStationView() {
        initComponents();
        
        currentWeaponPanel = new WeaponPanel();
        currentShieldPanel = new ShieldPanel();
        currentHangarPanel = new HangarPanel();
        
        jpWeapon.add(currentWeaponPanel);
        jpShield.add(currentShieldPanel);
        jpHangar.add(currentHangarPanel);
    }
        
    void setStation(SpaceStationToUI station) {
        jlAmmoPower.setText(Float.toString(station.getAmmoPower()));
        jlFuelUnits.setText(Float.toString(station.getFuelUnits()));
        jlNMedals.setText(Integer.toString(station.getnMedals()));
        jlName.setText(station.getName());
        jlShieldPower.setText(Float.toString(station.getShieldPower()));
        
        currentWeaponPanel.setWeapon(station);
        currentShieldPanel.setShield(station);
        currentHangarPanel.setHangar(station);
                
        DamageToUI damage = station.getPendingDamage();
        if ( damage != null ) {
            jlDamageShields.setText(Integer.toString(damage.getNShields()));
            String damageWeaponInfo = damage.getWeaponInfo();
            if ( damageWeaponInfo.equals("") )
                jtaDamageWeapons.setText("0");
            else
                jtaDamageWeapons.setText(damageWeaponInfo);
        } else {
            jlDamageShields.setText("0");
            jtaDamageWeapons.setText("0");
        }     
        
        repaint();
        revalidate();
    }
    
    ArrayList<Integer> getSelectedWeapons() {
        return currentWeaponPanel.getSelectedWeapons();
    }
    
    ArrayList<Integer> getSelectedShieldBoosters() {
        return currentShieldPanel.getSelectedShieldBoosters();
    }
    
    ArrayList<Integer> getSelectedWeaponsInHangar() {
        return currentHangarPanel.getSelectedWeapons();
    }
    
    ArrayList<Integer> getSelectedShieldBoostersInHangar() {
        return currentHangarPanel.getSelectedShieldBoosters();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlName = new javax.swing.JLabel();
        jlAmmoPowerLabel = new javax.swing.JLabel();
        jlShieldPowerLabel = new javax.swing.JLabel();
        jlFuelUnitsLabel = new javax.swing.JLabel();
        jlNMedalsLabel = new javax.swing.JLabel();
        jlAmmoPower = new javax.swing.JLabel();
        jlShieldPower = new javax.swing.JLabel();
        jlFuelUnits = new javax.swing.JLabel();
        jlNMedals = new javax.swing.JLabel();
        jpPendingDamage = new javax.swing.JPanel();
        jlDamageShieldsLabel = new javax.swing.JLabel();
        jlDamageWeaponsLabel = new javax.swing.JLabel();
        jlDamageShields = new javax.swing.JLabel();
        jsDamageWeapons = new javax.swing.JScrollPane();
        jtaDamageWeapons = new javax.swing.JTextArea();
        jpWeapon = new javax.swing.JPanel();
        jpShield = new javax.swing.JPanel();
        jpHangar = new javax.swing.JPanel();

        jlName.setBackground(new java.awt.Color(204, 204, 204));
        jlName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlName.setText("name");
        jlName.setOpaque(true);

        jlAmmoPowerLabel.setText("Potencia de ataque");

        jlShieldPowerLabel.setText("Potencia de defensa");

        jlFuelUnitsLabel.setText("Nivel de combustible");

        jlNMedalsLabel.setText("Medallas");

        jlAmmoPower.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlAmmoPower.setText("ammoPower");

        jlShieldPower.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlShieldPower.setText("shieldPower");

        jlFuelUnits.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlFuelUnits.setText("fuelUnits");

        jlNMedals.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlNMedals.setText("nMedals");

        jpPendingDamage.setBorder(javax.swing.BorderFactory.createTitledBorder("Castigo pendiente"));

        jlDamageShieldsLabel.setText("Escudos");

        jlDamageWeaponsLabel.setText("Armas");

        jlDamageShields.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlDamageShields.setText("sh");

        jsDamageWeapons.setBorder(null);
        jsDamageWeapons.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jtaDamageWeapons.setEditable(false);
        jtaDamageWeapons.setBackground(new java.awt.Color(238, 238, 238));
        jtaDamageWeapons.setColumns(20);
        jtaDamageWeapons.setRows(5);
        jtaDamageWeapons.setText("we");
        jtaDamageWeapons.setBorder(null);
        jsDamageWeapons.setViewportView(jtaDamageWeapons);

        javax.swing.GroupLayout jpPendingDamageLayout = new javax.swing.GroupLayout(jpPendingDamage);
        jpPendingDamage.setLayout(jpPendingDamageLayout);
        jpPendingDamageLayout.setHorizontalGroup(
            jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPendingDamageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDamageShieldsLabel)
                    .addComponent(jlDamageWeaponsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPendingDamageLayout.createSequentialGroup()
                        .addComponent(jlDamageShields)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jsDamageWeapons, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPendingDamageLayout.setVerticalGroup(
            jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPendingDamageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDamageShieldsLabel)
                    .addComponent(jlDamageShields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPendingDamageLayout.createSequentialGroup()
                        .addComponent(jlDamageWeaponsLabel)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(jsDamageWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpWeapon.setBorder(javax.swing.BorderFactory.createTitledBorder("Potenciadores de fuego"));

        jpShield.setBorder(javax.swing.BorderFactory.createTitledBorder("Potenciadores de defensa"));

        jpHangar.setBorder(javax.swing.BorderFactory.createTitledBorder("Hangar"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpWeapon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlAmmoPowerLabel)
                            .addComponent(jlShieldPowerLabel)
                            .addComponent(jlFuelUnitsLabel)
                            .addComponent(jlNMedalsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlShieldPower, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlAmmoPower, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(jlFuelUnits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlNMedals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpPendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpShield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpHangar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpPendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAmmoPowerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlShieldPowerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlFuelUnitsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlNMedalsLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAmmoPower)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlShieldPower)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlFuelUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlNMedals)))))
                .addGap(6, 6, 6)
                .addComponent(jpWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpShield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHangar, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlAmmoPower;
    private javax.swing.JLabel jlAmmoPowerLabel;
    private javax.swing.JLabel jlDamageShields;
    private javax.swing.JLabel jlDamageShieldsLabel;
    private javax.swing.JLabel jlDamageWeaponsLabel;
    private javax.swing.JLabel jlFuelUnits;
    private javax.swing.JLabel jlFuelUnitsLabel;
    private javax.swing.JLabel jlNMedals;
    private javax.swing.JLabel jlNMedalsLabel;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlShieldPower;
    private javax.swing.JLabel jlShieldPowerLabel;
    private javax.swing.JPanel jpHangar;
    private javax.swing.JPanel jpPendingDamage;
    private javax.swing.JPanel jpShield;
    private javax.swing.JPanel jpWeapon;
    private javax.swing.JScrollPane jsDamageWeapons;
    private javax.swing.JTextArea jtaDamageWeapons;
    // End of variables declaration//GEN-END:variables
}
