/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.EnemyToUI;

/**
 *
 * @author Miguel Ángel Fernández Gutiérrez, Sergio Quijano Rey
 */
public class CurrentEnemyView extends javax.swing.JPanel {

    /**
     * Creates new form CurrentEnemyView
     */
    public CurrentEnemyView() {
        initComponents();
    }
    
    void setEnemy(EnemyToUI enemy) {
        jlAmmoPower.setText(Float.toString(enemy.getAmmoPower()));
        jlShieldPower.setText(Float.toString(enemy.getShieldPower()));
        jlName.setText(enemy.getName());
        
        jlLootHangar.setText(Integer.toString(enemy.getLoot().getnHangars()));
        jlLootMedals.setText(Integer.toString(enemy.getLoot().getnMedals()));
        jlLootShields.setText(Integer.toString(enemy.getLoot().getnShields()));
        jlLootWeapons.setText(Integer.toString(enemy.getLoot().getnWeapons()));
        jlDamageShields.setText(Integer.toString(enemy.getDamage().getNShields()));
        jtaDamageWeapons.setText(enemy.getDamage().getWeaponInfo());
        jtaDamageWeapons.setWrapStyleWord(true);
        
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlName = new javax.swing.JLabel();
        jlAmmoPowerLabel = new javax.swing.JLabel();
        jlShieldPowerLabel = new javax.swing.JLabel();
        jlShieldPower = new javax.swing.JLabel();
        jlAmmoPower = new javax.swing.JLabel();
        jpLoot = new javax.swing.JPanel();
        jlLootWeaponsLabel = new javax.swing.JLabel();
        jlLootShieldsLabel = new javax.swing.JLabel();
        jlLootHangarLabel = new javax.swing.JLabel();
        jlLootHangar = new javax.swing.JLabel();
        jlLootWeapons = new javax.swing.JLabel();
        jlLootShields = new javax.swing.JLabel();
        jlLootMedals = new javax.swing.JLabel();
        jlLootMedalsLabel = new javax.swing.JLabel();
        jpDamage = new javax.swing.JPanel();
        jlDamageShieldsLabel = new javax.swing.JLabel();
        jlDamageWeaponsLabel = new javax.swing.JLabel();
        jlDamageShields = new javax.swing.JLabel();
        jsDamageWeapons = new javax.swing.JScrollPane();
        jtaDamageWeapons = new javax.swing.JTextArea();

        jlName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlName.setText("name");

        jlAmmoPowerLabel.setText("Potencia de fuego");

        jlShieldPowerLabel.setText("Potencia de defensa");

        jlShieldPower.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlShieldPower.setText("shieldPower");

        jlAmmoPower.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlAmmoPower.setText("ammoPower");

        jpLoot.setBorder(javax.swing.BorderFactory.createTitledBorder("Botín"));

        jlLootWeaponsLabel.setText("Armas");

        jlLootShieldsLabel.setText("Escudos");

        jlLootHangarLabel.setText("Tam. hangar");

        jlLootHangar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlLootHangar.setText("ha");

        jlLootWeapons.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlLootWeapons.setText("we");

        jlLootShields.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlLootShields.setText("sh");

        jlLootMedals.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlLootMedals.setText("me");

        jlLootMedalsLabel.setText("Medallas");

        javax.swing.GroupLayout jpLootLayout = new javax.swing.GroupLayout(jpLoot);
        jpLoot.setLayout(jpLootLayout);
        jpLootLayout.setHorizontalGroup(
            jpLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlLootShieldsLabel)
                    .addComponent(jlLootWeaponsLabel))
                .addGap(18, 18, 18)
                .addGroup(jpLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlLootWeapons, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jlLootShields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlLootHangarLabel)
                    .addComponent(jlLootMedalsLabel))
                .addGap(18, 18, 18)
                .addGroup(jpLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlLootHangar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlLootMedals, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpLootLayout.setVerticalGroup(
            jpLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpLootLayout.createSequentialGroup()
                        .addGroup(jpLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlLootHangarLabel)
                            .addComponent(jlLootHangar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlLootMedalsLabel)
                            .addComponent(jlLootMedals)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpLootLayout.createSequentialGroup()
                        .addGroup(jpLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlLootWeaponsLabel)
                            .addComponent(jlLootWeapons))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpLootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlLootShieldsLabel)
                            .addComponent(jlLootShields))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpDamage.setBorder(javax.swing.BorderFactory.createTitledBorder("Pérdidas"));

        jlDamageShieldsLabel.setText("Escudos");

        jlDamageWeaponsLabel.setText("Armas");

        jlDamageShields.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlDamageShields.setText("we");

        jsDamageWeapons.setBorder(null);

        jtaDamageWeapons.setEditable(false);
        jtaDamageWeapons.setBackground(new java.awt.Color(238, 238, 238));
        jtaDamageWeapons.setColumns(20);
        jtaDamageWeapons.setLineWrap(true);
        jtaDamageWeapons.setRows(5);
        jtaDamageWeapons.setText("sh");
        jtaDamageWeapons.setToolTipText("");
        jsDamageWeapons.setViewportView(jtaDamageWeapons);

        javax.swing.GroupLayout jpDamageLayout = new javax.swing.GroupLayout(jpDamage);
        jpDamage.setLayout(jpDamageLayout);
        jpDamageLayout.setHorizontalGroup(
            jpDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDamageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDamageShieldsLabel)
                    .addComponent(jlDamageWeaponsLabel))
                .addGap(44, 44, 44)
                .addGroup(jpDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDamageShields)
                    .addComponent(jsDamageWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDamageLayout.setVerticalGroup(
            jpDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDamageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpDamageLayout.createSequentialGroup()
                        .addComponent(jlDamageShields)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsDamageWeapons, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpDamageLayout.createSequentialGroup()
                        .addComponent(jlDamageShieldsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlDamageWeaponsLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDamage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlAmmoPowerLabel)
                                    .addComponent(jlShieldPowerLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlShieldPower)
                                    .addComponent(jlAmmoPower)))
                            .addComponent(jlName))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlAmmoPower)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlShieldPower))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlAmmoPowerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlShieldPowerLabel)))
                .addGap(18, 18, 18)
                .addComponent(jpLoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpDamage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlAmmoPower;
    private javax.swing.JLabel jlAmmoPowerLabel;
    private javax.swing.JLabel jlDamageShields;
    private javax.swing.JLabel jlDamageShieldsLabel;
    private javax.swing.JLabel jlDamageWeaponsLabel;
    private javax.swing.JLabel jlLootHangar;
    private javax.swing.JLabel jlLootHangarLabel;
    private javax.swing.JLabel jlLootMedals;
    private javax.swing.JLabel jlLootMedalsLabel;
    private javax.swing.JLabel jlLootShields;
    private javax.swing.JLabel jlLootShieldsLabel;
    private javax.swing.JLabel jlLootWeapons;
    private javax.swing.JLabel jlLootWeaponsLabel;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlShieldPower;
    private javax.swing.JLabel jlShieldPowerLabel;
    private javax.swing.JPanel jpDamage;
    private javax.swing.JPanel jpLoot;
    private javax.swing.JScrollPane jsDamageWeapons;
    private javax.swing.JTextArea jtaDamageWeapons;
    // End of variables declaration//GEN-END:variables
}
