/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JDialog;

/**
 *
 * @author Profe
 */
public class NamesCaptureView extends JDialog {
    private ArrayList<String> names = new ArrayList<>();

    public NamesCaptureView(MainWindow parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo (null);
        setTitle(parent.getAppName());
        jVersionLabel.setText(parent.getAppVersion());
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                // Se decide que cancelar la entrada de nombres supone no iniciar la aplicación
                System.exit(0);
            }
        });
        
    }
    
    void sendNames() {
        names.clear();
        names.add(jtName1.getText());
        names.add(jtName2.getText());
        if ( (Integer) jsNumPlayers.getValue() >= 3 )
            names.add(jtName3.getText());
        if ( (Integer) jsNumPlayers.getValue() >= 4 )
            names.add(jtName4.getText());
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jName1 = new javax.swing.JLabel();
        jName2 = new javax.swing.JLabel();
        jtName1 = new javax.swing.JTextField();
        jtName2 = new javax.swing.JTextField();
        jbStart = new javax.swing.JButton();
        jtName3 = new javax.swing.JTextField();
        jName3 = new javax.swing.JLabel();
        jName4 = new javax.swing.JLabel();
        jtName4 = new javax.swing.JTextField();
        jWelcomeLabel = new javax.swing.JLabel();
        jDeepspaceLabel = new javax.swing.JLabel();
        jVersionLabel = new javax.swing.JLabel();
        jsNumPlayers = new javax.swing.JSpinner();
        jNumPlayersLabel = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jName1.setText("Nombre 1: ");

        jName2.setText("Nombre 2: ");

        jbStart.setText("Empezar");
        jbStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStartActionPerformed(evt);
            }
        });
        jbStart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbStartKeyPressed(evt);
            }
        });

        jtName3.setEnabled(false);

        jName3.setText("Nombre 3: ");
        jName3.setEnabled(false);

        jName4.setText("Nombre 4: ");
        jName4.setEnabled(false);

        jtName4.setEnabled(false);

        jWelcomeLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jWelcomeLabel.setText("Bienvenido a");

        jDeepspaceLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jDeepspaceLabel.setText("Deepspace");

        jVersionLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jVersionLabel.setText("version");

        jsNumPlayers.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 1));
        jsNumPlayers.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsNumPlayersStateChanged(evt);
            }
        });

        jNumPlayersLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jNumPlayersLabel.setText("Seleccione número de jugadores:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jName3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtName3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jName4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtName4))
                        .addComponent(jWelcomeLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jDeepspaceLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jVersionLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jNumPlayersLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                            .addComponent(jsNumPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtName1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(jtName2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jWelcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDeepspaceLabel)
                    .addComponent(jVersionLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsNumPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNumPlayersLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName1)
                    .addComponent(jtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName2)
                    .addComponent(jtName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName3)
                    .addComponent(jtName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName4)
                    .addComponent(jtName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbStart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStartActionPerformed
        sendNames();
    }//GEN-LAST:event_jbStartActionPerformed

    private void jsNumPlayersStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsNumPlayersStateChanged
        switch((Integer) jsNumPlayers.getValue()) {
            case 2:
                jName3.setEnabled(false);
                jName4.setEnabled(false);
                jtName3.setEnabled(false);
                jtName4.setEnabled(false);
                break;
            case 3:
                jName3.setEnabled(true);
                jName4.setEnabled(false);
                jtName3.setEnabled(true);
                jtName4.setEnabled(false);
                break;
            case 4:
                jName3.setEnabled(true);
                jName4.setEnabled(true);
                jtName3.setEnabled(true);
                jtName4.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_jsNumPlayersStateChanged

    private void jbStartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbStartKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            sendNames();
        }
    }//GEN-LAST:event_jbStartKeyPressed


    ArrayList<String> getNames() {
        setVisible(true);
        return names;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDeepspaceLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jName1;
    private javax.swing.JLabel jName2;
    private javax.swing.JLabel jName3;
    private javax.swing.JLabel jName4;
    private javax.swing.JLabel jNumPlayersLabel;
    private javax.swing.JLabel jVersionLabel;
    private javax.swing.JLabel jWelcomeLabel;
    private javax.swing.JButton jbStart;
    private javax.swing.JSpinner jsNumPlayers;
    private javax.swing.JTextField jtName1;
    private javax.swing.JTextField jtName2;
    private javax.swing.JTextField jtName3;
    private javax.swing.JTextField jtName4;
    // End of variables declaration//GEN-END:variables
}
