/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import javax.swing.JPanel;
import deepspace.ShieldToUI;


/**
 *
 * @author Profe
 */
public class ShieldView extends JPanel {

    private boolean selected = false;
    
    ShieldView() {
        initComponents();
        setOpaque (selected);
    }
    
    void setShield(ShieldToUI s) {
        jlPower.setText(Float.toString(s.getBoost()));
        jlUses.setText(Integer.toString(s.getUses()));
        // hacer actualización efectiva
        repaint();
        // si se añaden componentes: revalidate();
    }
    
    boolean isSelected() {
        return selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlPowerLabel = new javax.swing.JLabel();
        jlPower = new javax.swing.JLabel();
        jlUsesLabel = new javax.swing.JLabel();
        jlUses = new javax.swing.JLabel();
        jlCardType = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jlPowerLabel.setText("Potencia");

        jlPower.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlPower.setText("power");

        jlUsesLabel.setText("Usos");

        jlUses.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlUses.setText("uses");

        jlCardType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlCardType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCardType.setText("ESCUDO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCardType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPowerLabel)
                            .addComponent(jlUsesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPower)
                            .addComponent(jlUses))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPowerLabel)
                    .addComponent(jlPower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsesLabel)
                    .addComponent(jlUses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jlCardType)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        setOpaque(selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlCardType;
    private javax.swing.JLabel jlPower;
    private javax.swing.JLabel jlPowerLabel;
    private javax.swing.JLabel jlUses;
    private javax.swing.JLabel jlUsesLabel;
    // End of variables declaration//GEN-END:variables
}
